version: '3.8'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "19001:19006"
    networks:
      - app-network

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "19002:19006"
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge